{"name": "Test Authorized endpoint - Failed Authentication", "status": "failed", "statusDetails": {"message": "AssertionError: Unexpected response content: {'code': '1207', 'message': 'User not found!'}\nassert {'code': '120...r not found!'} == {'code': 1207...r not found!'}\n  \n  Omitting 1 identical items, use -vv to show\n  Differing items:\n  {'code': '1207'} != {'code': 1207}\n  Use -v to get more diff", "trace": "@allure.title(\"Test Authorized endpoint - Failed Authentication\")\n    def test_authorized_failure():\n        with allure.step(\"Sending POST request to Authorized endpoint with invalid credentials\"):\n            response = requests.post(f\"{BASE_URL}/Authorized\", json=invalid_user)\n    \n        if response.status_code in [400, 404]:\n>           assert response.json() == {\"code\": 1207, \"message\": \"User not found!\"}, f\"Unexpected response content: {response.json()}\"\nE           AssertionError: Unexpected response content: {'code': '1207', 'message': 'User not found!'}\nE           assert {'code': '120...r not found!'} == {'code': 1207...r not found!'}\nE             \nE             Omitting 1 identical items, use -vv to show\nE             Differing items:\nE             {'code': '1207'} != {'code': 1207}\nE             Use -v to get more diff\n\nswagger_test.py:36: AssertionError"}, "steps": [{"name": "Sending POST request to Authorized endpoint with invalid credentials", "status": "passed", "start": 1715437881891, "stop": 1715437882864}], "start": 1715437881891, "stop": 1715437882867, "uuid": "20bbea6d-82fb-4ba4-8c0f-d8a9504d3312", "historyId": "331f821270927c9d49ee8e0f347ddc90", "testCaseId": "331f821270927c9d49ee8e0f347ddc90", "fullName": "swagger_test#test_authorized_failure", "labels": [{"name": "suite", "value": "swagger_test"}, {"name": "host", "value": "Romidamaru"}, {"name": "thread", "value": "14016-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "swagger_test"}]}